In [26]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, mean_squared_error

In [27]:
df=pd.read_csv(r"C:\Users\Rijitha\Downloads\gender_classification_v7.csv")

In [28]:
df

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,Male
1,0,14.0,5.4,0,0,1,0,Female
2,0,11.8,6.3,1,1,1,1,Male
3,0,14.4,6.1,0,1,1,1,Male
4,1,13.5,5.9,0,0,0,0,Female
...,...,...,...,...,...,...,...,...
4996,1,13.6,5.1,0,0,0,0,Female
4997,1,11.9,5.4,0,0,0,0,Female
4998,1,12.9,5.7,0,0,0,0,Female
4999,1,13.2,6.2,0,0,0,0,Female
5000,1,15.4,5.4,1,1,1,1,Male

In [29]:
df.head()

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,Male
1,0,14.0,5.4,0,0,1,0,Female
2,0,11.8,6.3,1,1,1,1,Male
3,0,14.4,6.1,0,1,1,1,Male
4,1,13.5,5.9,0,0,0,0,Female

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   long_hair                  5001 non-null   int64
 1   forehead_width_cm          5001 non-null   float64
 2   forehead_height_cm         5001 non-null   float64
 3   nose_wide                  5001 non-null   int64
 4   nose_long                  5001 non-null   int64
 5   lips_thin                  5001 non-null   int64
 6   distance_nose_to_lip_long  5001 non-null   int64
 7   gender                     5001 non-null   object
dtypes: float64(2), int64(5), object(1)
memory usage: 312.7+ KB

In [31]:
df.shape

(5001, 8)

In [32]:
print(df.isnull().sum())

long_hair                    0
forehead_width_cm            0
forehead_height_cm           0
nose_wide                    0
nose_long                    0
lips_thin                    0
distance_nose_to_lip_long    0
gender                       0
dtype: int64

In [33]:
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

df.head()

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,1
1,0,14.0,5.4,0,0,1,0,0
2,0,11.8,6.3,1,1,1,1,1
3,0,14.4,6.1,0,1,1,1,1
4,1,13.5,5.9,0,0,0,0,0

In [34]:
X = df.drop('gender', axis=1)
y = df['gender']

print(X.head())
print(y.head())

   long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0          1               11.8                 6.1          1          0
1          0               14.0                 5.4          0          0
2          0               11.8                 6.3          1          1
3          0               14.4                 6.1          0          1
4          1               13.5                 5.9          0          0

   lips_thin  distance_nose_to_lip_long
0          1                          1
1          1                          0
2          1                          1
3          1                          1
4          0                          0
0    1
1    0
2    1
3    1
4    0
Name: gender, dtype: int64

In [35]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (4000, 7)
Testing Data Shape: (1001, 7)

In [36]:
log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [37]:
y_pred_log = log_model.predict(X_test)

print(y_pred_log)

[1 0 0 ... 0 1 0]

In [38]:
accuracy = accuracy_score(y_test, y_pred_log)

print("Logistic Regression Accuracy:", accuracy)

Logistic Regression Accuracy: 0.9600399600399601

In [39]:
lin_model = LinearRegression()
lin_model.fit(X_train, y_train)

LinearRegression()

In [41]:
y_pred_lin = lin_model.predict(X_test)

print(y_pred_lin[:10])

[ 1.02855156 -0.02409002  0.23657446  1.03731035  1.09368999  0.78944543
  1.11270182  0.75821108  0.70862665 -0.0564477 ]

In [42]:
mse = mean_squared_error(y_test, y_pred_lin)

print("Linear Regression Mean Squared Error:", mse)

Linear Regression Mean Squared Error: 0.04190775067147379

In [43]:
comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted_Logistic': y_pred_log,
    'Predicted_Linear': y_pred_lin
})

In [44]:
comparison.head(10)

   Actual  Predicted_Logistic  Predicted_Linear
0       1                   1          1.028552
1       0                   0         -0.024090
2       0                   0          0.236574
3       1                   1          1.037310
4       1                   1          1.093690
5       0                   1          0.789445
6       1                   1          1.112702
7       1                   1          0.758211
8       1                   1          0.708627
9       0                   0         -0.056448